name: Check Babyschwimmen

on:
  schedule:
    - cron: "0 7,15 * * *"   
jobs:
  check:
    runs-on: ubuntu-latest
    
  

    env:
      BABY_SWIM_BOT_TOKEN: ${{ secrets.BABY_SWIM_BOT_TOKEN }}
      BABY_SWIM_BOT_CHAT_ID: ${{ secrets.BABY_SWIM_BOT_CHAT_ID }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: playwright install chromium

      - run: python src/check.py
